[workspace]
authors = ["Alistair English <hello@alistairenglish.com>"]
channels = ["conda-forge"]
name = "segspicious"
platforms = [{ platform = "linux-64", cuda = "12" }]
version = "0.1.0"

[dependencies]
python = ">=3.12"
numpy = "*"
pytorch-gpu = "*"
cuda-cudart-dev = "*"
torchvision = "*"
tqdm = "*"
matplotlib = "*"
hatchling = "*"
torchmetrics = ">=1.9.0,<2"

[pypi-dependencies]
segspicious = { path = ".", editable = true }
segspicious-experiments = { path = "experiments", editable = true }
torch-uncertainty = ">=0.13.0, <0.14"
lightning = ">=2.6.5, <3"
rich = ">=15.0.0, <16"

[feature.dev.dependencies]
pytest = "*"

[environments]
default = { features = ["dev"], solve-group = "default" }

[tasks]
test = "pytest segspicious/tests/ -v"
