[workspace]
authors = ["Alistair English <hello@alistairenglish.com>"]
channels = ["conda-forge"]
name = "segspicious"
platforms = [{ platform = "linux-64", cuda = "12" }]
version = "0.1.0"

[dependencies]
python = ">=3.12"
numpy = "*"
pytorch-gpu = "*"
cuda-cudart-dev = "*"
torchvision = "*"
tqdm = "*"
matplotlib = "*"
hatchling = "*"

[pypi-dependencies]
segspicious = { path = ".", editable = true }

[feature.dev.dependencies]
pytest = "*"

[environments]
default = { features = ["dev"], solve-group = "default" }

[tasks]
test = "pytest segspicious/tests/ -v"
